dist: bionic
os: linux

language: php

php:
  - 7.4
  - 8.0

services:
  - mysql

cache:
  directories:
    - vendor
    - node_modules

before_script:
  - cp .env.testing .env
  - sudo mysql -e 'create database sportr_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate

notifications:
  email:
    recipients:
      - me@felixgrohs.at
    on_success: never
    on_failure: always