dist: bionic

language: php

php:
  - 7.4
  - 8.0

services:
  - mysql

cache:
  directories:
    - vendor
    - node_modules

beforeScript:
  - cp .env.testing .env
  - sudo mysql -e 'create database sportr_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate